# This is a basic workflow to help you get started with Actions

name: Hello 

on:
  workflow_call:

jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
      - name: echo step
        run: echo "Hello this is a reusable workflow, welcome"
